---
sudo: required

language: python

services:
  - docker

before_install:
  - sudo apt-get -qq update

install:
  - pip install -r requirements.txt

env:
  - SCENARIO=centos

script: "molecule --debug test --scenario-name $SCENARIO"
