---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: ubuntu
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: chrony-ubuntu-bionic
    image: ubuntu:bionic
    command: /lib/systemd/systemd
    privileged: true
  - name: chrony-ubuntu-xenial
    image: ubuntu:xenial
    command: /lib/systemd/systemd
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        chrony_pool_region: []
        chrony_time_servers:
          - server0.molecule
          - server1.molecule
          - server2.molecule
          - server3.molecule
verifier:
  name: testinfra
